--CREATE DATABASE DB_JOB_PORTAL
USE DB_JOB_PORTAL
CREATE TABLE CANDIDATETB(
		CANDIDATE_ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
		CandidateEmailID VARCHAR(255) NOT NULL,
		FirstName VARCHAR(255) NOT NULL,
		LastName VARCHAR(255) NOT NULL,
		Username VARCHAR(255) NOT NULL,
		UserPassword VARCHAR(255),
		DateOfBirth DATE,
		Qualification  VARCHAR(255) NOT NULL,
		PassingYear DATE,
		CurrentCity VARCHAR(255) NOT NULL,
		Skills VARCHAR(255),
		ExperienceInYears INT NOT NULL DEFAULT 0
)

CREATE TABLE COMPANYTB(
	COMPANY_ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	CompanyName VARCHAR(255) NOT NULL,
	RecruiterName VARCHAR(255) NOT NULL,
	RecruiterEmailID VARCHAR(255) NOT NULL,
	FoundDate DATE,
	CompanyDescription VARCHAR(500) NOT NULL,
	CompanyLocation VARCHAR(255) NOT NULL,
	Username VARCHAR(255) NOT NULL,
	UserPassword VARCHAR(255)
)

CREATE TABLE JOBTB(
	JOB_ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	JobRole VARCHAR(255) NOT NULL,
	JobDescription VARCHAR(500) NOT NULL,
	JobType VARCHAR(255) NOT NULL,
	JobLocation VARCHAR(255) NOT NULL,
	SalaryMinimum BIGINT,
	SalaryMaximum BIGINT,
	RequiredExperience INT NOT NULL DEFAULT 0,
	RequiredSkills VARCHAR(255)
)
CREATE TABLE HasApplied_R(
		APPLICATION_ID BIGINT NOT NULL IDENTITY(10000,1) PRIMARY KEY,
		CANDIDATE_ID_FK INT FOREIGN KEY REFERENCES CANDIDATETB(CANDIDATE_ID),
		JOB_ID_FK INT FOREIGN KEY REFERENCES JOBTB(JOB_ID),
		JobStatus VARCHAR(255) NOT NULL DEFAULT 'ACTIVE',
		AppliedDate DATE,
)

CREATE TABLE JobPosting_R(
			POSTED_ID BIGINT NOT NULL IDENTITY(20000,1) PRIMARY KEY,
			JOB_ID_FK INT FOREIGN KEY  REFERENCES JOBTB(JOB_ID),
			COMPANY_ID_FK INT FOREIGN KEY REFERENCES COMPANYTB(COMPANY_ID),
			IsActive BIT, 
			PostingDate DATE
)
